color = "Always"
combine_control_expr = false
wrap_comments = true
brace_style = "PreferSameLine"
comment_width = 70
fn_single_line = false
condense_wildcard_suffixes = true
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = false
format_strings = true
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
match_arm_blocks = true
inline_attribute_width = 0
match_block_trailing_comma = false
merge_derives = true
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
